FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt -r linux-requirements.txt

COPY . .

EXPOSE 5000

ENTRYPOINT ["python"]
CMD ["tron.py"]
